### ISSUE TITLE
Cannot use the sslcontext for SSLServerSocket

### ISSUE THREAD

**Issue by ChillingVan** [robymus/simple-pem-keystore#1]
Thanks for your project. But I encount an issue.
I create a keystore with this project. But when I use it to a SSLContext, and create a SSLServerSocket, the client cannot finish the handshake.

When handshake, exception with no ciphr shared will be thrown.

The client app has no issue because it can connect to a server built with openssl.

**Comment by robymus** [comment]
Thanks for the report. I haven't encountered this one before, so please help me localizing it.

I have created a few sample gists with the code I used to test if everything works fine. Could you please try these in your setup to see if these also produce the error?

I created a test self-signed certificate using this script (use use any cert you like, however): https://gist.github.com/robymus/6b0f9c4449ac105a36462a512b9b7c97

I baseline SSLServerSocket with default keystore: https://gist.github.com/robymus/d286e7ac9eafd88cc43138f176f71635

SSLServerSocket with 'simplepem' - reading from pem, but no reloading:  https://gist.github.com/robymus/c23b937bf2d61dd358f92a470e78e889

SSLServerSocket with 'simplepemreload': https://gist.github.com/robymus/3e47153d70bd4fe86e4f81913ccecd8c

I have tested these all with `openssl s_client -connect localhost:4444`

If you encounter any problems, could you please send me your Java/OS version, output from openssl s_client and probably the SSL Context setup code?

**Comment by robymus** [comment]
I have encountered something similar to your case, when I set up a default ssl server socket, without simplepem keystore, using standard keystore and all default settings, not specifying protocol (eg. TLSv1.2) I got no cipher match from the test client. Can you try explicitly specifying the protocol when getting an SSLContext (eg. `SSLContext context = SSLContext.getInstance("TLSv1.2");`).

**Comment by robymus** [comment]
Also please try running tests (`gradle test`) on the current master branch, to see if integration tests pass - I have just upgraded these to work on MacOS as well. 

Also please refer to `*IntegrationTest.java` in https://github.com/robymus/simple-pem-keystore/tree/master/src/test/java/io/r2/simplepemkeystore for details on how I build an SSLContext using the keystore.

**Comment by ChillingVan** [comment]
Thank you very much. I double check your code and I think I use wrong KeyManagerFactory with the default one instead the getInstance("simplepem") one. I will retry it tomorrow. Thanks for your repository again.

**Comment by ChillingVan** [comment]
I create a SSLServerSocket on Android app. And I change the PKS8Spec to RSAPrivateCrtKeySpec in PemCertKey.java.  
I finally find a solution:
  I convert the original keystore to a BKS keystore:
```
            keyStore.load(
                    MultiFileConcatSource.fromFiles(
                            certFile,
                            keyFile
                    ).build(),
                    null // no password
            );

            KeyStore outKeyStore = KeyStore.getInstance("BKS", "BC");
            outKeyStore.load(null, null);
            outKeyStore.setKeyEntry("MyAlias", keyStore.getKey("server", new char[0]), new char[0], keyStore.getCertificateChain("server"));
```
