### ISSUE TITLE
Load multiple pems into a keystore with different aliases

### ISSUE THREAD

**Issue by benjefferies** [robymus/simple-pem-keystore#2]
It's a nice simple library to use but it would be good if it was possible to load multiple keys/certificates with different aliases

**Comment by robymus** [comment]
Thanks for the feedback, I will look into it.

**Comment by robymus** [comment]
I haven't touched this project for a while, so I rechecked the documentation in README.md, and I think there is support for what you are looking for:

```java
    // builder
    InputStream in = new ReloadablePemKeyStoreConfig()
            .addCertificate("server", new String[]{"server.pem"})
            .addCertificate("client", new String[]{"client.pem", "key.pem"})
            .withRefreshInterval(5)
            .asInputStream();
    KeyStore ks = KeyStore.getInstance("simplepemreload");
    ks.load(in);
```

The shorthand format for Let's Encrypt paths doesn't support this, but the full keystore config builder does, as shown above.

Also the keystore configuration JSON file (if not created by the builder) also support multiple aliases, like this:

```json
    {
      "refreshInterval": 3600,
      "certificates": {
        "alias1": [
          "/etc/letsencrypt/live/mydomain1.com/fullchain.pem",
          "/etc/letsencrypt/live/mydomain1.com/privkey.pem"
        ],
        "alias2": [
          "/etc/letsencrypt/live/mydomain2.com/fullchain.pem",
          "/etc/letsencrypt/live/mydomain2.com/privkey.pem"
        ],
      }
    }
```

This file then can be loaded as keystore file.

Or does it not work correctly like this? (Now I noticed that this case is not covered by the tests, I will add some to cover it shortly)

**Comment by benjefferies** [comment]
I saw this and thought it was exactly what I needed however I realised it was only limited to file references whereas we're dynamically downloading keys. We could save it to a tmp location each time as a work around I suppose?

Would be nicer if we could just pass the string of them keys

**Comment by robymus** [comment]
I see what you are looking for.  I think it can be added easily, I will get on it :)

**Comment by robymus** [comment]
The new features are ready to go. You can check in detail in the documentation in [README.md](https://github.com/robymus/simple-pem-keystore/blob/v0.2/README.md).

What you can do now is, use the simplepem provider and craft the input source as:
```
alias: alias1
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----

alias: alias2
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
```

It will load these as separate certificates with their own aliases. You can use the MultiFileConcatSource convenience class to construct this. it supports now adding aliases, and I also added an addBytes(byte[]) method, to help you build this structure from in-memory certificates.

```java
    KeyStore ks = KeyStore.getInstance("simplepem");
    ks.load(
            new MultiFileConcatSource()
                .alias("alias1")
                    .addBytes( /* your certificates as byte[] */)
                .alias("alias2")
                .creationDate(Instant.now())
                    .add("cert2.pem")
                    .add("key2.pem")
                .build(),
            new char[0] // no password
    );
```

You can also add creation date as metadata (defaults to current time) and use the reloading KeyManagerFactory on top of the new simplepem to reload certificates on the fly. [See example.](https://github.com/robymus/simple-pem-keystore/blob/1a4aabab06afae5b3dd7b6f987b84b35677c9c2f/src/test/java/io/r2/simplepemkeystore/ReloadablePemKeyStoreIntegrationTest.java#L117-L166)

Pushing it to maven central takes like forever, but it should be there soon.
In the meantime you can build it yourself or get a prebuilt jar from [Releases](https://github.com/robymus/simple-pem-keystore/releases/tag/v0.2).

**Comment by benjefferies** [comment]
This is beautiful. Thanks dude!
