### ISSUE TITLE
any chance to support of PKCS1 key file(starting with "BEGIN RSA PRIVATE KEY")?

### ISSUE THREAD

**Issue by hago** [robymus/simple-pem-keystore#3]
You did amazing work, the pem keystore is a gift！ Thank you very much.

But I ran into this error: 

> java.security.cert.CertificateException: Invalid chunk in input
	at io.r2.simplepemkeystore.spi.PemStreamParser.parse(PemStreamParser.java:86)

when I was trying to deal with a key file.
According the source code, private key file with "-----BEGIN RSA PRIVATE KEY" is not supported yet. Do you have plan to support that format?

**Comment by robymus** [comment]
I will do it right away :)

To be honest, I thought I've added this already, but I did it in my other java crypto project.

Thanks for reporting, and also for the encouragement.

**Comment by robymus** [comment]
Should be good now, I created version 0.3 including PKCS#1 key support (eg. BEGIN RSA PRIVATE KEY).

You can find it in releases: https://github.com/robymus/simple-pem-keystore/releases/tag/v0.3 - or compile it yourself.

It will take some time for it to show up in Maven Central.

Let me know if it works in your usecase and I will close this issue then.

**Comment by hago** [comment]
it works very well, thanks!
